# Generated by Django 3.0.7 on 2020-06-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=15)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=60)),
                ('password', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date expense incurred')),
                ('item', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CLO', 'Clothing'), ('FOOD', 'Food'), ('FUEL', 'Fuel'), ('RENT', 'Rent'), ('UTI', 'Utilities'), ('PHN', 'Phone'), ('EDU', 'Education'), ('MISC', 'Miscellaneous')], max_length=4)),
                ('amount', models.FloatField()),
                ('notes', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User')),
            ],
        ),
    ]
