# Generated by Django 3.0.7 on 2020-07-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='category',
            field=models.CharField(blank=True, choices=[('CLO', 'Clothing'), ('FOOD', 'Food'), ('FUEL', 'Fuel'), ('RENT', 'Rent'), ('UTI', 'Utilities'), ('PHN', 'Phone'), ('EDU', 'Education'), ('MISC', 'Miscellaneous')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of expense'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
