# Generated by Django 3.0.7 on 2020-07-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
