# Generated by Django 3.0.7 on 2020-07-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20200717_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of expense'),
        ),
    ]
